class ClusteredFormats(object):
    def __dir__(self):
        return ['not_avalaible', 'csv', 'spreadsheets', 'word', 'geographical', 'rdf', 'pdf', 'archives', 'text', 'other_machine_readable', 'databases', 'apis', 'other']
    not_avalaible = [
    u'',
    u'n/a',
    u'unverified'
    ]

    csv = [
    u'csv',
    u'1_csv_format / zip',
    u'CSV',
    u'comma separated variable (csv)',
    u'csv ',
    u'csv (wfs)',
    u'csv (zip)',
    u'csv / zip',
    u'csv file',
    u'csv-datei',
    u'csv-semicolon delimited',
    u'csv-tab delimited',
    u'csv.zip',
    u'csv/utf8',
    u'csw',
    u'cvs',
    u'text/tsv',
    u'tsv',
    u'zip (csv utf8)',
    u'zip (csv)',
    u'zip:csv',
    u'xls en csv',
    u'xls, csv',
    ]

    spreadsheets = [
    u'xls',
    u'1 / xls',
    u'52 / xlsx',
    u'XLS',
    u'api/vnd.google-spreadsheet',
    u'application/vnd.\noasis.opendocument.\nspreadsheet',
    u'application/vnd.ms-excel',
    u'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    u'application/x-msexcel',
    u'excel',
    u'excel (xml)',
    u'google spreadsheet',
    u'ms excel',
    u'ods',
    u'xls ',
    u'xls / xlsx',
    u'xls zip',
    u'xls, pdf',
    u'xls-html',
    u'xls1',
    u'xlsm',
    u'xlsx',
    u'xlsx ',
    u'zip: xls',
    u'zip:xls'
    ]

    word = [
    u'.doc',
    u'ods',
    u'application/vnd.ms-word',
    u'doc',
    u'docx',
    u'ms word',
    u'odt',
    u'rtf',
    u'word doc',
    u'word document'
    ]

    geographical = [
    u'shp, gml, geojson, csv',
    u'KML',
    u'SHAPE',
    u'application/dxf',
    u'application/vnd.google-earth.kmz]',
    u'application/x-mmz',
    u'arcgis, kml (google earth)',
    u'arcinfo ascii-grid',
    u'dwg',
    u'dxf',
    u'esri',
    u'esri arcsde 8.x/sde 3.x',
    u'esri shapefile',
    u'esri shapefile ',
    u'esri shapefiles',
    u'g7t, gpx, kmz, ovl, plt, tk, trk',
    u'geojson',
    u'georss',
    u'geotif',
    u'geotiff',
    u'gis',
    u'gml',
    u'gml    ',
    u'gml (sf-0)',
    u'gml / api',
    u'gml /api',
    u'gml, html, jpg',
    u'gpx',
    u'grafika',
    u'grid',
    u'grid esri',
    u'gtfs',
    u'i quadranti .dxf',
    u'karte',
    u'kartenviewer',
    u'kml ',
    u'kml, kmz',
    u'kml, shp',
    u'kmx',
    u'kmz',
    u'ogc/sos',
    u'ogc/wfs',
    u'ogc/wms',
    u'rar:shp',
    u'shapefile',
    u'shp',
    u'shp / zip',
    u'shp, geojson',
    u'shp, mxd, zip',
    u'shx',
    u'sps',
    u'spss',
    u'tfw',
    u'wfs',
    u'wfs, kml (google earth)',
    u'wfs, wms, kml',
    u'wms',
    u'wms (ogc)',
    u'wms, kml (google earth)',
    u'wmt-s',
    u'wmts',
    u'zip (gpx)',
    u'zip (shp)',
    u'zip | shape-files + excel',
    u'zip | shapefile',
    u'zip, shp',
    u'zip-kml',
    u'zip:shape',
    u'zip:shp',
    u'zip | kml en json',
    u'zip:dxf'
    ]

    rdf = [
    u'application/rdf xml',
    u'RDF',
    u'api/sparql',
    u'application/rdf xml',
    u'application/rdf+xml',
    u'example/rdf+xml',
    u'example/rdfa',
    u'html+rdfa',
    u'linked data api, rdf json',
    u'meta/void',
    u'n-triple',
    u'n-triples',
    u'n3',
    u'owl',
    u'rdf/turtle',
    u'rdf/xml, marcxml',
    u'rdfa',
    u'skos rdf',
    u'skos webservice',
    u'sparql',
    u'sparql endpoint',
    u'sparql web form',
    u'text/ntriples',
    u'text/turtle',
    u'ttl',
    u'turtle'
    ]

    pdf = [
    u'7 / pdf',
    u'pdf ',
    u'pdf'
    ]

    archives = [
    u'7z',
    u'ZIP',
    u'application/x-zip-compressed',
    u'bz2',
    u'bz2:nt',
    u'gz (txt)',
    u'gzip',
    u'gzip+txt',
    u'rar',
    u'tar.bz2',
    u'txt / zip',
    u'zip ',
    u'zip (xls, doc, pdf)'
    ]

    text = [
    u'HTML',
    u'PDF',
    u'TEXT',
    u'TXT'
    u'ascii',
    u'ascii-txt',
    u'e-mail',
    u'eps',
    u'htm',
    u'htm ',
    u'html ',
    u'html5',
    u'shtml',
    u'text/plain',
    u'texto',
    u'web',
    u'web application',
    u'web page',
    u'webmapservice',
    u'webpage',
    u'webservice',
    u'websevice',
    u'website'
    ]

    other_machine_readable = [
    u'JSON',
    u'XML',
    u'application/rss+xml',
    u'atom',
    u'json ',
    u'json (wfs)',
    u'rss',
    u'rss+xml',
    u'rss, xml',
    u'text/rss+xml',
    u'xml ',
    u'xml (zip)',
    u'xml / zip',
    u'xml rpc',
    u'xml-rss',
    u'xml: oai-pmh dublin core',
    u'xsd',
    u'xsl',
    u'xslt',
    u'xxml',
    u'zip / xml',
    u'zip:xml',
    u'zip:xml en csv',
    u'zip|xml'
    u'zip:json'
    ]

    databases = [
    u'access.mdb ',
    u'database',
    u'dbase',
    u'dbf',
    u'mdb',
    u'mdb (zip)',
    u'msaccess',
    u'sql',
    u'sqlite 3',
    u'zip (sql + jpeg)',
    u'zip (sql)',
    u'zip:mdb'
    ]

    apis = [
    u'api',
    u'api/search',
    u'api: xml en jpg',
    u'csv/api',
    u'csv/webservice/api',
    u'ensearch api',
    u'open search api, xml',
    u'open search api, xml ',
    u'rest'
    ]

    other = [
    u'ai',
    u'altro', 
    u'application/force-download',
    u'aree',
    u'application/octet-stream',
    u'application/octet-stream+esri',
    u'application/xml+xls+pdf',
    u'ascii grid',
    u'ascii grid, xls, shp, csv',
    u'ascii-grid (arcinfo)',
    u'asmx',
    u'asp',
    u'aspx',
    u'axd',
    u'blender v.2.49b',
    u'cat\xe1logos',
    u'cav',
    u'cd-rom',
    u'csv ods pdf',
    u'csv per garmin. tom tom',
    u'csv, kml',
    u'csv, kml, xls',
    u'csv, sas, spss',
    u'csv, shp',
    u'csv, xls',
    u'csv, xls, pdf',
    u'csv, xml, xsd',
    u'cvs:xml',
    u'data',
    u'dbf, prj, sbn, sbx, shp, shx en xml',
    u'derzeit ist der download nur als *.xls m\xf6glich',
    u'do',
    u'exe',
    u'garmin',
    u'ger',
    u'gif',
    u'gif, wld',
    u'gjson',
    u'h',
    u'hmml',
    u'hmtl',
    u'hoja de c\xe1lculo',
    u'html, json, xml, csv, tsv, tag',
    u'html, json, xml, csv, tsv, tag, kml',
    u'html, zip, csv, txt',
    u'http, csv, pdf, xls, kml, shp, ascii grid',
    u'http, csv, xls',
    u'http, csv, xls, pdf',
    u'ical',
    u'icalendar',
    u'image/jpeg',
    u'image/png',
    u'imagen',
    u'imagen/texto',
    u'iso',
    u'it%2fit%2fareac%2f',
    u'jp2',
    u'jpeg',
    u'jpeg, png, gif',
    u'jpg',
    u'jrss',
    u'js',
    u'js\'",            " type=\'text/javascript',
    u'json, csv',
    u'json, xml',
    u'linee',
    u'lzma',
    u'media wiki xml',
    u'mid',
    u'mif',
    u'mif\u2212mid',
    u'mp3',
    u'mpg',
    u'mult',
    u'multipart/alternative',
    u'odc',
    u'odp',
    u'netcdf',
    u'nodi',
    u'ntf',
    u'oai-pmh',
    u'oai-pmh (xml repons)',
    u'oai-pmh (xml respons)',
    u'oai-pmh en sru (respons in xml)',
    u'odata protocol',
    u'ordner',
    u'otros',
    u'ovl',
    u'ovl (bin\xe4r5)',
    u'parco_veicoli_aprile_2014.7z',
    u'pbf',
    u'pdf, xls',
    u'pdf/word',
    u'php',
    u'ply',
    u'png',
    u'png, gif',
    u'por',
    u'ppt',
    u'pptx',
    u'prj',
    u'punti',
    u'py',
    u'ress',
    u'rest, json',
    u'rest, soap, wfs, kml ',
    u'rest, soap, wfs, kml (google earth)',
    u'rest, soap, wms, kml',
    u'rest, soap, wms, kml (google earth)',
    u'rest, soap, wms, wfs, kml',
    u'rest, soap, wms, wfs, kml ',
    u'rest, soap, wms, wfs, kml (google earth)',
    u'sav',
    u'sbn',
    u'sbx',
    u'scv',
    u'service',
    u'sld',
    u'soap',
    u'svg',
    u'tab',
    u'tabella',
    u'tif',
    u'tiff',
    u'tiff-lzw',
    u'tms',
    u'tomtom',
    u'url',
    u'uso_suolo_dusaf4_2012_polygon.zip',
    u'va ',
    u'varios',
    u'viewservice',
    u'viewservice, html, xml, skos, yml',
    u'waf',
    u'wcs',
    u'wsdl',
    u'wsdl, xsd',
    u'xla',
    u'xlb',
    u'xml / html / tab / zip',
    u'xml, csv, html',
    u'xms',
    u'zip: spss',
    u'zip:dhx',
    u'zip:mkz'
    ]
