# Data gathered from thedatahub.org

rdf_formats = ['N-Triples',
               'OWL',
               'RDF',
               'RDF/N3',
               'RDF/NT',
               'RDF/XML',
               'TURTLE',
               'Turtle',
               'application/n3',
               'application/rdf xml',
               'application/rdf+xml',
               'application/rdf+xml ',
               'application/rdfs',
               'application/turtle',
               'application/x-nquads',
               'application/x-ntriples',
               'example/n3',
               'example/n3 ',
               'example/ntriples',
               'example/owl',
               'example/rdf',
               'example/rdf xml',
               'example/rdf+json ',
               'example/rdf+n3',
               'example/rdf+xml',
               'example/turtle',
               'example/x-turtle',
               'linked data',
               'mapping/OWL',
               'mapping/d2r',
               'mapping/owl',
               'mapping/rdfs',
               'meta/dcat',
               'meta/rdf+schema',
               'meta/rdf+xml',
               'meta/rdf-schema',
               'meta/rdf-schema ',
               'meta/turtle',
               'meta/urtle',
               'meta/void',
               'meta/void\t',
               'n3',
               'nt',
               'nt:meta',
               'nt:transparency-international-corruption-perceptions-index',
               'owl',
               'rdf',
               'rdf+xml',
               'rdf+xml ',
               'rdf, nt',
               'rdf, owl',
               'rdf, void',
               'rdf/turtle',
               'rdf/xml',
               'rdf:products:org:openfoodfacts',
               'text/n3',
               'text/ntriples',
               'text/rdf+n3',
               'text/ttl',
               'text/turtle',
               'ttl',
               'ttl:e1:csv',
               'turtle']
compressed_formats = [ '7z:ttl',
               'Compressed tarfile containing n-triples',
               'GZIP::NQUADS',
               'bz2:nt',
               'compressed tarfile containing n-triples',
               'gz:nq',
               'gz:nt',
               'gz:ttl',
               'gz:ttl:owl',
               'gzip:ntriples',
               'gzip:rdf/xml',
               'rdf (gzipped)',
               'ttl.bzip2' ]
html_formats = [ 'HTML+RDFa',
               'HTML+RDFa ',
               'HTML, RDF',
               'HTML/RDF',
               'RDFa',
               'XHTML+RDFa',
               'example/HTML+RDFa',
               'example/rdfa',
               'html+RDFa ',
               'html+rdfa',
               'html+rdfa ' ]
endpoints  = [
               'RDF endpoint',
               'RDF, SPARQL+XML',
               'SPARQ/JSON',
               'SPARQL',
               'SPARQL/JSON',
               'SPARQL/XML',
               'api/linked-data',
               'api/sparql',
               'api/sparql ',
               'api/dcat',
               'rdf, sparql',
               'html, rdf, dcif',
               'rdf, csv, xml',
               'RDF/XML, HTML, JSON',
               'RDF, SPARQL+XML',
               'sparql'
             ]
bad_formats = [
               'RDF/XML, Turtle, HTML', #html page
               'XML, RDF+XML, Turtle and JSON', #html page
              ] 
